export const TRANSACTION_CATEGORY = {
  HOUSING: "HOUSING",
  TRANSPORTATION: "TRANSPORTATION",
  FOOD: "FOOD:",
  ENTERTAINMENT: "ENTERTAINMENT",
  HEALTH: "HEALTH",
  UTILITY: "UTILITY",
  SALARY: "SALARY",
  EDUCATION: "EDUCATION",
  OTHER: "OTHER",
};

export const TRANSACTION_PAYMENT_METHOD = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  BANK_SLIP: "BANK_SLIP",
  CASH: "CASH",
  PIX: "PIX",
  OTHER: "OTHER",
};

export const TRANSACTION_TYPE = {
  DEPOSIT: "DEPOSIT",
  EXPENSE: "EXPENSE",
  INVESTMENT: "INVESTMENT",
};
